# Generated by Django 3.0.5 on 2020-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_piwa', models.CharField(max_length=50)),
                ('surowce', models.TextField(max_length=500)),
                ('drożdże', models.CharField(max_length=100)),
                ('fermentacja', models.CharField(choices=[('rd', 'rehydratyzacja drożdży'), ('sd', 'starter drożdżowy')], default='rd', max_length=30)),
                ('objętość_brzeczki_w_fermentorze', models.IntegerField(default='20')),
            ],
        ),
    ]
