# Generated by Django 3.0.5 on 2020-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='końcowa_wartość_BLG',
            field=models.FloatField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wpis',
            name='startowa_wartość_BLG',
            field=models.FloatField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wpis',
            name='temperatura_dodania_drożdży',
            field=models.IntegerField(default='19', max_length=3),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='objętość_brzeczki_w_fermentorze',
            field=models.IntegerField(default='20', max_length=2),
        ),
    ]
