# Generated by Django 3.0.5 on 2020-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20200423_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpis',
            name='objętość_brzeczki_w_fermentorze',
        ),
        migrations.RemoveField(
            model_name='wpis',
            name='temperatura_dodania_drożdży',
        ),
        migrations.AddField(
            model_name='wpis',
            name='objetosc',
            field=models.IntegerField(default='20', max_length=2, verbose_name='objętość brzeczki w fermentatorze [litry]'),
        ),
        migrations.AddField(
            model_name='wpis',
            name='temperatura_D_D',
            field=models.IntegerField(default='19', max_length=3, verbose_name='temperatura dodania drożdży [°C]'),
        ),
    ]
